czs_user:
    resource: "@CZSUserBundle/Resources/config/routing.yml"
    prefix:   /


# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc