<?php
/**
 * Created by PhpStorm.
 * User: pbborel
 * Date: 14/11/2014
 * Time: 09:11
 */
namespace CZS\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}